# Generated by Django 4.0.4 on 2022-05-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_workexperience_is_current_alter_skill_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ('start_date',)},
        ),
        migrations.AddConstraint(
            model_name='workexperience',
            constraint=models.UniqueConstraint(fields=('is_current',), name='unique is_current'),
        ),
    ]
